### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [HeartArmy/MovieBrowser#2]
The following features are checked in the readme but **not shown in the GIF**. These features are not given points.

- Add a rounded corners for the images using the Glide transformations

In order for us to count these towards your submission, please record another GIF that captures these features. Once you do, please push your updates and submit your assignment again through the course portal **within 48 hours** from the posted deadline so that we can regrade it.

**Comment by HeartArmy** [comment]
Added the updated gif with the rounded image.
